### ISSUE TITLE
Img logo URL broken on https://gsoc.rocket.chat/

### ISSUE THREAD

**Issue by Davide95** [shubhsherl/GSoC-Contribution-Leaderboard#17]
In the homepage, line 25, the URL is in HTTP instead of HTTPS.
This can lead to a mixed content vulnerability and also break the UI for all the people like me who have stricter rule on the browser (e.g. they're using HTTPS Everywhere extension).
Consider moving the image somewhere in which HTTPS can be used.

**Comment by shubhsherl** [comment]
Fixed by this commit ae6b80d1253efe9921479f9e54fb4b87e47eba14
