### ISSUE TITLE
Improve refresh script to reduce runtime and eliminate occasional miscounting of Issue, PRs

### ISSUE THREAD

**Issue by shubhsherl** [shubhsherl/GSoC-Contribution-Leaderboard#20]
There are some miscounting of PRs and Issues. Probably because of large fetching time and updating database. To figure out an efficient way of updating.

**Comment by Sing-Li** [comment]
@shubhsherl  can you please tell us what the current refresh script does - in pseudo-code if possible, similar to:

```
loop
    get list of students from sqlite
     repeat for each student in list 
         call  Github/getPRs(student.github.ID) API
     end do
end loop
```

**Comment by shubhsherl** [comment]
Current refresh script:
```
loop
    get repos from organisation from API
       update repos
       repeat for each marked repo from sqlite
          get contributors, PRs and Issues of marked repo from API
          update the counts in sqlite of students
       end do
end loop
```

**Comment by Sing-Li** [comment]
@shubhsherl:

1)  please explain what `update repos` do ?
2)  since we have the student's github ids - does the Github API allow query by their IDs instead?

**Comment by shubhsherl** [comment]
@Sing-Li 
1) update repo fetches all the repo of organization(In case a new repo is added, it will be updated in SQLite).
2) Yes, the API allows query by ID, but instead, I am using repo wise data and updating the contributors.
We can also use the method of the query by ID, but it will take a lot of time in for all contributors( but I guess less time if we iterate over GSoC student IDs only). I will check and update if it works.

**Comment by Sing-Li** [comment]
@shubhsherl   The objective of this optimization is to:  minimize the number of calls to the Github API required.  And secondarily to minimize the number of "long running" calls within the minimized subset.

You will need some current call frequency and time statistics to do this properly and systematically.

Do you have these stats? 

If not, instrumenting the calling code to gather the statistics should be one of the first steps.

**Comment by shubhsherl** [comment]
@Sing-Li 
It seems that fetching data by the query is giving the correct response, and there is no miscounting. So we can fetch the GSoC List every 10 min, and All List once or twice a day(as it takes a lot of time). 
GSoC List: For each user, 3 API calls are required.
All List: For each marked repo populate users from issues/PRs/contributors(number of calls vary from repo to repo). And then for each user, 3 API calls are required.

**Comment by shubhsherl** [comment]
The issue is with the rate limit of GitHub API for, in a minute we can fetch only [30 search resources of Github](https://developer.github.com/v3/search/#rate-limit). So the request of the user outside this 30 limit, is not updated.

**Comment by Sing-Li** [comment]
@shubhsherl  are you sure you are doing **SEARCH** operation in your code?   If so, can you switch the algorithm to use **GET** or **FETCH** instead?   The later has authenticated limit of [5000 API calls per hour](https://developer.github.com/v3/#rate-limiting) as per docs.

Perhaps you can make fetch all --> 100% on demand and manual.  Only run when needed.

And put delays between each API call ensuring rate limit is never reachable.

@shubhsherl  @kb0304  -  I fail to see why one would need **SEARCH** for the leaderboard update.

**Comment by shubhsherl** [comment]
The problem is solved in the first release.
