### ISSUE TITLE
Add ranking / count to rows

### ISSUE THREAD

**Issue by Pratyush1197** [shubhsherl/GSoC-Contribution-Leaderboard#32]
Introduction of serial number will help the users to know the current position of a particular person on leaderboard

**Comment by Sing-Li** [comment]
For some orgs, they may want to see the ranking explicitly.  

For long lists, it is quite useful for participant lower in the list to see their ranking.

Also for long list, it will provide at a glance TOTAL participation easily.

When adding this feature,  please **MAKE SURE** it is disabled by default and can be configured on/off by using the `.env` variables.

**Comment by shubhsherl** [comment]
e2606ae65fd74334ec15bd9fa58b67903e868ad5
