### ISSUE TITLE
Specify how to change sort order

### ISSUE THREAD

**Issue by Sing-Li** [shubhsherl/GSoC-Contribution-Leaderboard#40]
In the README, add a section called "Leaderboard Sort Order"

and describe how to change the sort order if needed

**Comment by shubhsherl** [comment]
ecb4371cde5664cbf8e1871bdfa32a6296534503

**Comment by Sing-Li** [comment]
Sorry,  we need a separate section as well.   And instruction on how to change the:

**combination default sort order**

Our way of doing the default "combo condition" sort order MAY NOT be applicable to all GSoC organizations.  They need to be able to change it.   This is why a separate section, and more instructions are required.

**Comment by shubhsherl** [comment]
f8343184efcdea3f3fd59c030ee81e658b759f82
