### ISSUE TITLE
Sort order must include "add date" instead of alphabetical

### ISSUE THREAD

**Issue by Sing-Li** [shubhsherl/GSoC-Contribution-Leaderboard#45]
Alphabeta sorting makes no sense on a leaderboard.

Allow the final base sort order to be based on date the name is added.   

For example, for all the 0 0 0 users, the earliest to join should show up at the top of the 0 0 0 portion. 

Right now, it is alphabetical.

**Comment by shubhsherl** [comment]
e2606ae65fd74334ec15bd9fa58b67903e868ad5
