### ISSUE TITLE
Some of the opened issues vanished on the leaderboard count

### ISSUE THREAD

**Issue by Pratyush1197** [shubhsherl/GSoC-Contribution-Leaderboard#48]
I am facing this problem as I opened few issues earlier. At that time the issues were appearing on GSOC leaderboard but now the are not appearing though the issues are still open. 
I am not sure is it a bug or they disappeared due to some other reason

**Comment by shubhsherl** [comment]
@Pratyush1197  As per the directed link, the RocletChat/feature-request is not marked for counting. It will show when it will be marked.

**Comment by shubhsherl** [comment]
I am closing this issue if you find any other discrepancy please open it again.
