### ISSUE TITLE
PRs and commits counts are not correct

### ISSUE THREAD

**Issue by thayannevls** [shubhsherl/GSoC-Contribution-Leaderboard#5]
I've made two PRs, one at [RocketChat/docs](https://github.com/RocketChat/docs/pull/1076) and other at [RocketChat/Rocket.Chat](https://github.com/RocketChat/Rocket.Chat/pull/13443), but the https://gsoc.rocket.chat/ are only counting one PR.

**Comment by kb0304** [comment]
@thayannevls We have to mark repos from which we count the commits, RocketChat/docs was not marked, it is now. The leaderboard is showing now that you have 2 open PRs. I'm closing this issue, if you find any other discrepancy please open it again.

**Comment by knrt10** [comment]
@kb0304 same issue for [RocketChat/Docker.Official.Image](https://github.com/RocketChat/Docker.Official.Image) would you please mark it. My contributions are not shown
