### ISSUE TITLE
[BUG] Total count of contributors is not visible

### ISSUE THREAD

**Issue by fliptrail** [shubhsherl/GSoC-Contribution-Leaderboard#51]
**Describe the bug**
The text color of total number of contributors is not visible. It is white in color which makes it invisible to the user.

**Expected behavior**
It should be visible

**Screenshots**
![Screenshot from 2019-03-25 04-19-48](https://user-images.githubusercontent.com/40834245/54887110-3ebafe00-4eb5-11e9-9b47-588249a28a7e.png)
![Screenshot from 2019-03-25 04-20-02](https://user-images.githubusercontent.com/40834245/54887111-3ebafe00-4eb5-11e9-8515-821b51436182.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 72.0

**Comment by shubhsherl** [comment]
@fliptrail It was intentionally invisible. We can make it visible to the users, after the review of @Sing-Li

**Comment by fliptrail** [comment]
@shubhsherl Looks odd, but okay!

**Comment by shubhsherl** [comment]
#52
