### ISSUE TITLE
[BUG] PR's made in Leaderboard repo count as Open PR's but they do not get displayed when clicking on the option

### ISSUE THREAD

**Issue by fliptrail** [shubhsherl/GSoC-Contribution-Leaderboard#53]
**Describe the bug**

For me, it shows that I have 10 PR's open.
10 PR's = 9 PR's on Rocket.Chat org + 1 PR on Leader board repo.
But when I click on the corresponding link to see a list of my PR's, I can only see the PR's open on the Rocket.Chat org. This is because of the corresponding filter applied. 
This miscounting does lead to some confusion. 
I suggest that contributions on Leaderboard repo are shown separately, so that the filter can be applied easily.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 72

**Comment by shubhsherl** [comment]
@fliptrail Leaderboard repo PRs are not counted. There is already a bug related to the miscounting.
Two problems:
* If your PR is closed, Open PRs is still keeping its count.
* If your PR(let PR_1) is merged before PR_2, although PR_2 was created before PR_1.
#50 
#49
